### ISSUE TITLE
dockerignore stat ./flink-1.13.0 does  not exist

### ISSUE THREAD

**Issue by sisterBigEye** [pyflink/playgrounds#11]
when i execute the command "docker build --tag pyflink/playgrounds:1.13.0-rc0 ." ,error occur :
![image](https://user-images.githubusercontent.com/18341322/117597948-3a2b2f80-b179-11eb-9fd7-c825a50500c0.png)
dockerignore stat ./flink-1.13.0 does  not exist.
i have download the file:
apache-flink-libraries-1.13.0.tar.gz and apache-flink-1.13.0.tar.gz into image directory.
waiting for your answer,thanks a lot

**Comment by dianfu** [comment]
You need also extract [flink-1.13.0](https://dist.apache.org/repos/dist/release/flink/flink-1.13.0/), e.g flink-1.13.0-bin-scala_2.11.tgz to directory flink-1.13.0

**Comment by sisterBigEye** [comment]
> You need also extract [flink-1.13.0](https://dist.apache.org/repos/dist/release/flink/flink-1.13.0/), e.g flink-1.13.0-bin-scala_2.11.tgz to directory flink-1.13.0

感谢回复，我需要建一个名为flink-1.13.0的文件夹，然后把flink-1.13.0-bin-scala_2.11.tgz下载到文件夹吗？使用python

**Comment by dianfu** [comment]
直接解压，我记得名字就是flink-1.13.0

**Comment by dianfu** [comment]
https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka_2.11/1.13.0/flink-sql-connector-kafka_2.11-1.13.0.jar

**Comment by sisterBigEye** [comment]
感谢大佬
